### ISSUE TITLE
Html parser for markdone

### ISSUE THREAD

**Issue by afcastano** [omarrr/markdone#1]
Hi, I have created this: https://github.com/afcastano/markdown-todo-parser

It is an html parser for files that follow your markdone definition.

It's in a very early stage, but I needed it for another project, just thought you should know about it in case someone ask you for one.

=)

**Comment by omarrr** [comment]
This is awesome. I'm sorry I didn't see the notification for this when it happened. Really like the use of checkboxes for your output. Thanks for sharing.
